#!/usr/bin/env bash

# MIT license (c) 2022 https://github.com/slowpeek
# Homepage: https://github.com/slowpeek/hddtemp

set -eu
shopt -s nullglob

# A very basic replacement for hddtemp tool missing from Ubuntu
# 22.04. It requires smartctl (smartmontools package).

SCRIPT_VERSION=0.1+git

bye() {
    echo "$@" >&2
    exit 1
}

version() {
    echo "hddtemp $SCRIPT_VERSION"
    exit
}

usage() {
    local self=${BASH_SOURCE[0]##*/}

    cat <<EOF
USAGE --

${self}
    show temps for all sd and nvme disks

${self} /dev/sda ...
    show temps for selected disks

Options:
-h, --help                 Show usage
-V, --version              Show version

Homepage https://github.com/slowpeek/hddtemp
EOF

    exit
}

opts=$(getopt -o hV -l help,version -- "$@") || exit
eval set -- "$opts"

while (( $# )); do
    case $1 in
        -h|--help)
            usage ;;
        -V|--version)
            version ;;
        --)
            shift
            break ;;
    esac
done

type -P smartctl &>/dev/null || bye smartctl is not available
(( EUID )) && bye smartctl requires root permissions, run with sudo

# If no args supplied, assume all sd and nvme disks.
(( $# )) || set -- /dev/sd? /dev/nvme?n?

items=() l1=0 l2=1
for disk; do
    [[ $disk == /dev/* ]] || continue

    name=
    temp=

    readarray -t lines < <(smartctl -i -l scttempsts "$disk" 2>&1)
    for line in "${lines[@]}"; do
        case $line in
            'Device Model:'*)
                read -r _ _ name <<< "$line" ;;
            'Current Temperature:'*)
                read -r _ _ temp _ <<< "$line" ;;
        esac
    done

    (( ${#disk} > l1 )) && l1=${#disk}
    (( ${#name} > l2 )) && l2=${#name}

    items+=("$disk:" "${name:-?}" "${temp:-?}")
done

printf "%-$((l1+1))s  %-${l2}s  %s\n" "${items[@]}"
