* Motivation

The original hddtemp is not maintained far too long. Due to that it was removed
from the official repositories of Ubuntu (since 22.04) and Debian (since
12). This tool can be used instead to print the temps:

#+begin_example
  $ sudo hddtemp-lt
  /dev/sda:  WDC WD10EFRX-68FYTN0  28
  /dev/sdb:  KINGSTON SHFS37A240G  30
#+end_example

* Requirements

- =smartctl= (=smartmontools= package)
  - NVMe support: =smartctl= v6.5+

* Usage

+ =hddtemp-lt= :: Show temps for all =sd= and =nvme= disks.
+ =hddtemp-lt /dev/sda ..= :: Show temps for selected disks

Options:

- =-h, --help= :: Show usage
- =-q= :: Suppress warnings
- ~-u, --units=C|F~ :: Use Celsius (default) or Fahrenheit scale
- =-V, --version= :: Show version

Output is aligned into columns. Device models can contain spaces like
/WDC WD10EFRX-68FYTN0/ or /Samsung SSD 950 PRO 256GB/ so fields are
separated with at least two spaces.

* Installation

Fetch the archive either from releases or from the development branch,
extract it and put =hddtemp-lt= under =/usr/local/bin/=

In case you downloaded the script alone from github by a raw link, be
sure to manually make it executable.

If you'd like point a =hddtemp= symlink to it:

#+begin_example
  sudo ln -s hddtemp-lt /usr/local/bin/hddtemp
#+end_example
